# Generated by Django 6.0.2 on 2026-05-26 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_profile_subscription'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subscriber',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
