# Generated by Django 6.0.5 on 2026-07-08 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
