# Generated by Django 6.0.5 on 2026-06-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Additional Information'),
        ),
        migrations.AlterField(
            model_name='report',
            name='is_resolved',
            field=models.BooleanField(default=False, verbose_name='Checked'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(choices=[('spam', 'Spam'), ('abusive', 'Violence Or Abusive'), ('copyright', 'Copyright'), ('inappropriate', 'Sexual Content Or Inappropriate'), ('other', 'Other')], max_length=20),
        ),
    ]
